name: Dev Branches

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v3

  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.6
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile --check-files

      - name: Audit Dependencies
        run: yarn audit

  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Lint
      - uses: actions/cache@v2.1.6
        id: restore-build
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        run: yarn lint:ci

      - name: Commit formatted files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Fix formatting"

  build:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Build
      - uses: actions/cache@v2.1.6
        id: restore-build
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        run: yarn build:ci

  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4

      - name: Test
      - uses: actions/cache@v2.1.6
        id: restore-build
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        run: yarn test:ci
