name: "Lockfile changes"
on:
  pull_request:
    branches: [master, stable]

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:

      - name: Yarn Lock Changes
        uses: Simek/yarn-lock-changes@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          collapsibleThreshold: '25'
          failOnDowngrade: 'false'
          path: 'yarn.lock'
          updateComment: 'true'
