name: Dev Branches

on:
  push:
    branches:
      - "*"
      - "!master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Lint commits
        uses: wagoid/commitlint-github-action@v3

      - name: Lint
        run: yarn lint

      - name: Set up Node ${{ matrix.node-version }}
        uses: actions/setup-node@v2.1.5
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: yarn --frozen-lockfile

      - name: Audit Dependencies
        run: yarn audit

      - name: Build
        run: yarn build:ci

      - name: Test
        run: yarn test:ci
