name: Types Generating

on:
  pull_request:
    branches: [master]

  push:
    branches: [master]

jobs:
  code:
    name: Type checking code
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Type check
        run: yarn types
